name: 'stock_pipeline'
version: '1.0.0'
config-version: 2

profile: 'stock_pipeline'

model-paths:   ["models"]
seed-paths:    ["seeds"]
test-paths:    ["tests"]
snapshot-paths:["snapshots"]
macro-paths:   ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  stock_pipeline:
    staging:
      +materialized: view
      +schema: stg
    marts:
      +materialized: incremental
      +schema: mart
      +unique_key: [ticker, trade_date]
